apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: topicsecretcf
spec:
  apiKey:
    secretKeyRef:
      name: binding-messagehubcf
      key: api_key
  kafkaAdminUrl:
    secretKeyRef:
      name: binding-messagehubcf
      key: kafka_admin_url
  topicName: exampletwo
  numPartitions: 3
  replicationFactor : 3
  configs :
    - name: retentionMs
      value: 2592000000