# Constants used to package the operator for operator hub

operator_name: event-streams-topic
channel_name: alpha
maturity: alpha
image: cloudoperators/event-streams-topic
crd:
    - kind: Topic
      description: An operator for managing Topics for Event Streams on IBM Cloud
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Topic",
            "metadata": {
            "name": "mytopic"
            },
            "spec": 
              {"bindingFrom": {"name": "myes-binding"},
               "topicName": "myTopic"}
        }
      resources:
        - kind: Secret
          version: v1
        - kind: ConfigMap
          version: v1
        - kind: Topic
          version: v1alpha1
        - kind: Binding
          version: v1alpha1
      specDescriptors:        
        - description: TopicName is the displayed Topic name
          displayName: TopicName
          path: topicName
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: NumPartitions is the number of partitions for the Topic
          displayName: NumPartitions
          path: numPartitions
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: ReplicationFactor is the replication factor for the Topic
          displayName: ReplicationFactor
          path: replicationFactor
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: Configs is an array of configuration parameters for the Topic
          displayName: Configs
          path: configs
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: Binding object that holds the secret for Event Streams credentials
          displayName: BindingFrom
          path: bindingFrom
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: APIKey is the API key for the Topic's Event Stream service
          displayName: ApiKey
          path: apiKey
          x-descriptors:
            - 'urn:alm:descriptor:text' 
        - description: KafkaAdminURL is the kafka admin URL for the Topic's Event Stream service
          displayName: KafkaAdminUrl
          path: kafkaAdminUrl
          x-descriptors:
            - 'urn:alm:descriptor:text'        
      statusDescriptors:
        - description: Detailed message on current status
          displayName: Message
          path: message
          x-descriptors:
            - 'urn:alm:descriptor:text'    
        - description: Current state for the Topic
          displayName: State
          path: state
          x-descriptors:
            - 'urn:alm:descriptor:text' 