apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/name: topic-operator
  name: topic-operator
  namespace: topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topic-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: topic-operator
    spec:
      containers:
      - args:
        - "-logtostderr=true"
        - "-v=5"
        command:
        - ./manager
        image: PLACEHOLDER
        imagePullPolicy: Always
        name: topic
      serviceAccountName: topic-operator